#!/usr/bin/env zsh

function install {
    if command -v cargo &> /dev/null; then
        echo "Rust is already installed"
        return
    fi

    curl https://sh.rustup.rs -sSf | sh -s -- -y
}

install || echo Failed to install Rust

