#!/usr/bin/env zsh

NAME="SDKMan"

function install {
  if [[ ! -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    source <(curl -s "https://get.sdkman.io?rcupdate=false") || return 1
    source "$SDKMAN_DIR/bin/sdkman-init.sh" || return 2
  else 
    echo "✅ $NAME is already installed"
  fi
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"

