#!/usr/bin/env bash

NAME="SDKMan"

function install {
  if [[ ! -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    source <(curl -s "https://get.sdkman.io?rcupdate=false")
    source "$SDKMAN_DIR/bin/sdkman-init.sh"
  else 
     echo "✅ $NAME is already installed"
  fi
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME"

