#!/usr/bin/env zsh

function install {
    if command -v entr &> /dev/null; then
        echo "Entr is already installed"
        return
    fi

    SUDO=$(get-sudo)
    TMP="$(mktemp -d)"

    cd $TMP
    git clone https://github.com/eradman/entr.git
    cd entr
    ./configure
    make test
    PREFIX=~/.local make install
}

install || echo Failed to install Entr

