#!/usr/bin/env zsh

NAME="fzf"
VERSION='0.54.2'
ARCH=$(uname -m)

_BIN="$HOME/.local/bin/fzf"

function install {
    if command -v fzf &> /dev/null; then
        if [[ $(fzf --version) =~ $VERSION ]]; then
            echo "✅ $NAME is up to date"
            return
        fi
    fi

    if [[ $ARCH -eq "x86_64" ]]; then
        ARCH="amd64"
    elif [[ $ARCH -eq "arm64" ]]; then
        ARCH="arm8"
    else
        echo "❌ $ARCH is not supported"
        return 1
    fi

    [[ -e "$_BIN" ]] && rm "$_BIN"
    wget -qO- "https://github.com/junegunn/fzf/releases/download/v$VERSION/fzf-$VERSION-linux_$ARCH.tar.gz" \
        | tar -xz -C $HOME/.local/bin || return 2
    chmod +x "$_BIN" || return 3
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"
