#!/usr/bin/env zsh

NAME="Rust"

function install {
    if command -v cargo &> /dev/null; then
        echo "✅ $NAME is already installed"
        return
    fi

    curl https://sh.rustup.rs -sSf | sh -s -- -y || return 1
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"

