#!/usr/bin/env zsh

NAME="Zoxide"
function install {
    if command -v zoxide &> /dev/null; then
        echo "✅ $NAME is already installed"
        return
    fi

    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME"

