#!/usr/bin/env zsh

NAME='atuin'
VERSION='18.4.0-beta.1'
ARCH=$(uname -m)

_BIN="$HOME/.local/bin/atuin"
_LIB="$HOME/.local/lib/atuin"

function install {
    if command -v atuin &> /dev/null; then
        if [[ $(atuin --version) =~ $VERSION ]]; then
            echo "✅ $NAME is up to date"
            return
        fi
    fi

    [[ -e "$_BIN" ]] && rm -rf "$_BIN"
    [[ -d "$_LIB" ]] && rm -rf "$_LIB/{*,.*}"
    mkdir -p $_LIB || return 3
    tar -C "$_LIB" --strip-components 1 -xzf <(curl -sL "https://github.com/atuinsh/atuin/releases/download/v$VERSION/atuin-$ARCH-unknown-linux-gnu.tar.gz") || return 4
    ln -s "$_LIB/atuin" "$_BIN" || return 5
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"
