#!/usr/bin/env zsh

NAME='atuin'
VERSION='18.4.0-beta.1'

_LIB="$HOME/.local/lib/atuin"
_BIN="$HOME/.local/bin/atuin"

function install {
    if command -v atuin &> /dev/null; then
        if [[ $(atuin --version) =~ $VERSION ]]; then
            echo "✅ $NAME is up to date"
            return
        fi
    fi

    ARCH=$(uname -m)
    if [ $ARCH != "x86_64" ]; then
        echo "❌ $ARCH is not supported"
        return
    fi

    if [[ -d "$_LIB" ]]; then
        rm -rf "$_LIB/{*,.*}"
    else
        mkdir -p ~/.local/lib/atuin 
    fi
    tar -C "$_LIB" --strip-components 1 -xzf <(curl -sL "https://github.com/atuinsh/atuin/releases/download/v$VERSION/atuin-x86_64-unknown-linux-gnu.tar.gz")

    if [[ ! -e "$_BIN" ]]; then
        ln -s "$_LIB/atuin" "$_BIN"
    fi

    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME"
