#!/usr/bin/env zsh

NAME='go'
VERSION='go1.22.1'
ARCH=$(uname -m)
_LIB="$HOME/.local/lib/go"
_BIN="$HOME/.local/bin/go"
function install {
    if command -v go &> /dev/null; then
        if [[ $(go version) =~ $VERSION ]]; then
            echo "✅ $NAME is up to date"
            return
        fi
    fi

    if [[ $ARCH -eq "x86_64" ]]; then
        ARCH="amd64"
    elif [[ $ARCH -eq "arm64" ]]; then
        ARCH="arm64"
    else
        echo "❌ $ARCH is not supported"
        return 1
    fi

    [[ -d "$_LIB" ]] && rm "$_LIB"
    [[ -e "$_BIN" ]] && rm "$_BIN"
    mkdir -p "$_LIB" || return 1
    zsh -c "tar -C ~/.local/lib -xzf <(curl -sL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz)" || return 2
    ln -s "$_LIB/bin/go" "$_BIN" || return 3
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"
