#!/usr/bin/env zsh

NAME="Entr"

function install {
    if command -v entr &> /dev/null; then
        echo "✅ $NAME is already installed"
        return
    fi

    SUDO=$(get-sudo)
    TMP="$(mktemp -d)"

    cd $TMP
    git clone https://github.com/eradman/entr.git
    cd entr
    ./configure
    make test
    PREFIX=~/.local make install
    echo "✅ $NAME installed successfully"
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME"

