#! /usr/bin/env zsh


function install {
  if [[ ! -s "$HOME/.local/bin/oh-my-posh" && ! -d $XDG_CACHE_HOME/oh-my-posh ]]; then
    curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
  else 
    echo Oh My Posh already installed
  fi
}

install || echo Failed to install Oh My Posh
