#!/usr/bin/env zsh

NAME="Entr"

function install {
    if command -v entr &> /dev/null; then
        echo "✅ $NAME is already installed"
        return
    fi

    (
        TMP="$(mktemp -d)"
        cd $TMP
        git clone https://github.com/eradman/entr.git || return 1
        cd entr
        ./configure || return 2
        make testa || return 3
        PREFIX=~/.local make install || return 4
        echo "✅ $NAME installed successfully"
    ) || return $?
}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"

