#!/usr/bin/env zsh

function install {
    if command -v go &> /dev/null; then
        echo "Go is already installed"
        return
    fi

    ARCH=$(uname -m)
    if [ $ARCH != "x86_64" ]; then
        echo "$ARCH is not supported"
        return
    fi

    mkdir -p ~/.local/lib
    zsh -c "tar -C ~/.local/lib -xzf <(curl -sL https://go.dev/dl/go1.21.1.linux-amd64.tar.gz)"
    ln -s ~/.local/lib/go/bin/go ~/.local/bin/
}

install || echo Failed to install Go
