#!/usr/bin/env zsh

NAME="Neovim"
DISTRO="$(awk -F= '/^ID_LIKE/{print $2}' /etc/os-release)"

function install {
    # if command -v nvim &> /dev/null; then
    #     echo "✅ $NAME is already installed"
    #     return
    # fi

    if [ "$(id -u)" -eq 0 ]; then
        SUDO=""
    else
        if ! command -v sudo &> /dev/null; then
            echo "❌ sudo is not installed. Please install sudo or run as root."
            return 1
        fi
        SUDO="sudo"
    fi

    if [[ "$DISTRO" -eq "debian" ]]; then
        $SUDO add-apt-repository -y ppa:neovim-ppa/unstable || return 2
        $SUDO apt-get update || return 3
        $SUDO apt-get install -y neovim ripgrep fd-find || return 3
    elif [[ "$DISTRO" =~ "rhel" ]]; then
        $SUDO yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm || return 4
        $SUDO yum install -y neovim python3-neovim || return 5
    else
        echo "❌ $DISTRO is not supported"
    fi
    echo "✅ $NAME installed successfully"

}

echo "⚙️  Installing $NAME"
install || echo "❌ Failed to install $NAME: $?"

