".config/nvim":
  type: "git-repo"
  url: "git@github.com:Joniator/nvim.git"
  refreshPeriod: "168h"

".config/zsh/antidote":
  type: "git-repo"
  url: "https://github.com/mattmc3/antidote.git"
  refreshPeriod: "168h"

".local/bin/nvim":
  type: "file"
  url: "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.appimage"
  refreshPeriod: "168h"
  executable: true

