.config/nvim":
  type: "git-repo"
  url: "https://codeberg.org/JonnyB/nvim.git"
  refreshPeriod: "168h"

".config/zsh/antidote":
  type: "git-repo"
  url: "https://github.com/mattmc3/antidote.git"
  refreshPeriod: "168h"
