#! /usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ -f ~/.zshenv ]] 
then 
    . ~/.zshenv
fi

eval "$(oh-my-posh init bash --config $XDG_CONFIG_HOME/omp/jonnyb.omp.yaml)"

source $XDG_CONFIG_HOME/zsh/config/util.zsh
source $XDG_CONFIG_HOME/zsh/config/alias.zsh

