" Set custom path for pathogen and autoload
set rtp^=$XDG_CONFIG_HOME/vim
execute pathogen#infect()

set viminfofile=$XDG_CONFIG_HOME/vim/viminfo

syntax on
filetype plugin indent on

set tabstop=2
set shiftwidth=2
set expandtab
set number
set modeline

colo darkblue
