" Set custom path for pathogen and autoload
set rtp^=$XDG_CONFIG_HOME/vim
execute pathogen#infect()

set viminfofile=$XDG_CONFIG_HOME/vim/viminfo

syntax on
filetype plugin indent on

set tabstop=2
set shiftwidth=2
set expandtab
set number
set modeline

colo darkblue

" Configuration templates
let g:tmpl_search_paths=[ ".config/vim/templates" ]

" Configuration vim Airline
set laststatus=2

let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1

" Configuration NERDTree
map <F5> :NERDTreeFocus<CR>
let NERDTreeShowHidden=1

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9

" Configuration Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
