#!/usr/bin/env zsh

# Fix Inappropriate ioctl for device
export GPG_TTY=$(tty)
eval "$(direnv hook zsh)"

# Create XDG directories if they don't already exist
if [[ ! -d "$XDG_DATA_HOME" ]]; then mkdir -p "$XDG_DATA_HOME"; fi
if [[ ! -d "$XDG_STATE_HOME" ]]; then mkdir -p "$XDG_STATE_HOME"; fi
if [[ ! -d "$XDG_CACHE_HOME" ]]; then mkdir -p "$XDG_CACHE_HOME"; fi

# Use friendly folder names
zstyle ':antidote:bundle' use-friendly-names 'yes'

source ${ZDOTDIR:-~}/antidote/antidote.zsh
antidote_dir=${ZDOTDIR:-~}/antidote
plugins_txt=${ZDOTDIR:-~}/plugins
static_file=${ZDOTDIR:-~}/plugins.zsh
config_folder=${ZDOTDIR:-~}/config

# Generate a static plugin file.
if [[ $plugins_txt -nt $static_file || $config_folder -nt $static_file || ! -s $static_file ]]; then
  (
    . $antidote_dir/antidote.zsh
    [[ -e $plugins_txt ]] || touch $plugins_txt
    envsubst < $plugins_txt | antidote bundle >$static_file
  )
fi

autoload -Uz $antidote_dir/functions/antidote

# source the static plugins file
source $static_file

# cleanup
unset antidote_dir plugins_txt static_file alias_folder

