#! /usr/bin/env zsh

CMD_PATH=$(cmd.exe /c "echo %USERPROFILE%" 2> /dev/null | tr -d "\r")
WINDOWS_HOME=$(wslpath $CMD_PATH)

echo "Copying files to $WINDOWS_HOME"
mkdir -p $WINDOWS_HOME/.config

echo "Copying wezterm config"
cp -r "$HOME/.config/wezterm" "$WINDOWS_HOME/.config/wezterm"
