---
- name: Root setup
  hosts: localhost
  become: yes
  tasks:

    - name: Add nushell repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.fury.io/nushell/ /"
        state: present
        update_cache: no

    - name: Add nushell GPG key
      ansible.builtin.apt_key:
        url: https://apt.fury.io/nushell/gpg.key
        state: present

    - name: Add nvim repository
      ansible.builtin.apt_repository:
        repo: "ppa:neovim-ppa/unstable"
        state: present
        update_cache: no

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install package from repository
      ansible.builtin.apt:
        state: present
        pkg: 
          - nushell
          - neovim
          - build-essential   # Neovim Treesitter
          - unzip             # Oh my Posh installer

    - name: Install package from deb
      ansible.builtin.apt:
        state: present
        deb: https://github.com/twpayne/chezmoi/releases/download/v2.62.6/chezmoi_2.62.6_linux_amd64.deb

    - name: Set nu as default shell
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        shell: /usr/bin/nu

- name: User setup
  hosts: localhost
  tasks:
    - name: Check if SSH key exists
      ansible.builtin.stat:
        path: "~/.ssh/id_ed25519"
      register: ssh_key

    - name: Init chezmoi
      ansible.builtin.command:
        cmd: >- 
          chezmoi init --apply --exclude="scripts"
          {{ "ssh://git@codeberg.org/JonnyB/dotfiles.git" if ssh_key.stat.exists else "https://codeberg.org/JonnyB/dotfiles.git" }}
        creates: "~/.local/share/chezmoi/"

    - name: Setup oh-my-posh
      ansible.builtin.shell:
        cmd: "curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin"
        creates: "~/.local/bin/oh-my-posh"

