name: Local tests

on:
  push:
  pull_request:

jobs:
  Test_Install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: > 
          "$HOME/.local/bin/chezmoi" data;
          install-sdkman;
          install-nvim;
