name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run local tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - run: $HOME/.local/bin/chezmoi data
      - run: zsh -c "install-sdkman; source setup-sdkman; sdk version"
      - run: zsh -c "install-nvim; nvim --version"

  deploy:
    name: Build, test and deploy docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            joniator/dotfiles:${{ github.sha }}
            joniator/dotfiles:latest
            ghcr.io/joniator/dotfiles:${{ github.sha }}
            ghcr.io/joniator/dotfiles:latest
